Repository wpmudev/shared-ui, pull requests merged in 2018-11, with the labels that each got.

#173 [Enhance] Side navigation styles and sticky class.
  index.html
  scss/_sidenav.scss
Labels: enhancement

#177 [Improvement] Accordion blocks responsive design.
  index.html
  scss/_accordions.scss
Labels: enhancement

#178 [Improvement] Select dropdown options with icons.
  index.html
  js/select.js
  scss/_colors.scss
  scss/_select.scss
Labels: enhancement

#180 [Fix] Side navigation input overlapping notices
  CHANGELOG.md
  scss/_sidenav.scss
Labels: bug

#181 [Enhance] Improve buttons styles and its variations
  CHANGELOG.md
  index.html
  scss/_buttons.scss
  scss/_colors.scss
  scss/_forms.scss
Labels: enhancement, new

#185 Remove transition from sortable items - "move" as a event affected by
  scss/_box-builder.scss
Labels: bug

#186 Fix/buttons
  CHANGELOG.md
  scss/_buttons.scss
  scss/_colors.scss
Labels: bug, enhancement

#184 👌 Added accessibility color for checkbox, radio, tabs and wp editor
  CHANGELOG.md
  scss/_color-accessibility.scss
Labels: enhancement

#187 [Enhance] Wysiwyg editor content links need to be the same blue from SUI.
  CHANGELOG.md
  scss/sui-wp-editor.scss
Labels: enhancement
