Repository wpmudev/shared-ui, pull requests merged in 2021-11, with the labels that each got.

#347 🐛 fix(radio): Fieldset element unnecessary styles removal.
  assets/scss/shared-ui/_tabs.scss
Labels: bug

#374 🐛 fix(icons): Add `site-health` and `import-export` icons.
  assets/fonts/wpmudev-plugin-icons.eot
  assets/fonts/wpmudev-plugin-icons.svg
  assets/fonts/wpmudev-plugin-icons.ttf
  assets/fonts/wpmudev-plugin-icons.woff
  assets/fonts/wpmudev-plugin-icons.woff2
  assets/scss/shared-ui/_icons.scss
  page-icons.html
Labels: enhancement

#376 SASS deprecation warnings.
  ISSUE_TEMPLATE/bug_report.md
  assets/css/wordpress-rtl.css
  assets/css/wordpress-rtl.min.css
  assets/css/wordpress.css
  assets/css/wordpress.min.css
  assets/scss/shared-ui/_accordions.scss
  assets/scss/shared-ui/_ace-editor.scss
  assets/scss/shared-ui/_box-builder.scss
  assets/scss/shared-ui/_box-selectors.scss
  assets/scss/shared-ui/_boxes.scss
  assets/scss/shared-ui/_buttons.scss
  assets/scss/shared-ui/_calendar-range.scss
  assets/scss/shared-ui/_colorpickers.scss
  assets/scss/shared-ui/_header.scss
  assets/scss/shared-ui/_layout.scss
  assets/scss/shared-ui/_list.scss
  assets/scss/shared-ui/_modals.scss
  assets/scss/shared-ui/_multistrings.scss
  assets/scss/shared-ui/_notifications.scss
  assets/scss/shared-ui/_pagination.scss
  assets/scss/shared-ui/_progress-bars.scss
  assets/scss/shared-ui/_radio-checkbox.scss
  assets/scss/shared-ui/_scores.scss
  assets/scss/shared-ui/_select2.scss
  assets/scss/shared-ui/_summary.scss
  assets/scss/shared-ui/_tables.scss
  assets/scss/shared-ui/_toggles.scss
  assets/scss/shared-ui/_variables.scss
  assets/scss/shared-ui/shared-ui.scss
  assets/scss/showcase/components/_page-colours.scss
  gulpfile.js
  package-lock.json
  package.json
Labels: breaking

#377 **changelog:** Set file new structure.
  CHANGELOG.md
  CHANGELOG_ARCHIVE.md
Labels: documentation
