Repository wpmudev/shared-ui, pull requests merged in 2021-12, with the labels that each got.

#378 fix(upgrade): Revamp markup to add video section.
  CHANGELOG.md
  assets/js/shared-ui/upload.js
  assets/scss/shared-ui/_upgrade-page.scss
  package.json
  page-upgrade-demo.html
  page-upgrade.html
  page-uploads-file.html
  page-uploads-image.html
Labels: breaking

#370 new(upload-files): Enable drag and drop to upload files.
  assets/js/shared-ui/upload.js
  assets/scss/shared-ui/_upload.scss
  page-uploads-file.html
  page-uploads-image.html
Labels: new

#380 new(upload-files): Enable drag and drop to upload files.
  assets/js/shared-ui/upload.js
  page-uploads-file.html
  page-uploads-image.html
Labels: new

#348 new(modals): Add option for disabling open/close modal effects.
  assets/js/shared-ui/modal-dialog.js
  assets/scss/shared-ui/_tabs.scss
  page-modals.html
Labels: new

#382 new(upload-files): Drag and drop upload files.
  assets/js/shared-ui/upload.js
  assets/scss/shared-ui/_upload.scss
  page-uploads-file.html
  page-uploads-image.html
Labels: bug

#372 fix(modal): Scroll bar triggers the closing action.
  assets/scss/shared-ui/_modals.scss
  assets/scss/shared-ui/_variables.scss
Labels: bug

#385 new(checkbox): Focus state styles.
  assets/scss/shared-ui/_colors.scss
  assets/scss/shared-ui/_radio-checkbox.scss
Labels: new

#383 new(modals): Add option for disabling open/close modal effects.
  assets/js/shared-ui/modal-dialog.js
  page-modals.html
Labels: new

#390 fix(select2): "Smart Search" needs focus state.
  assets/js/shared-ui/select2.full.js
  assets/scss/shared-ui/_select2.scss
Labels: improvement

#391 fix(gulp): Not publishing to Github when release.
  .gitignore
  gulpfile.js
  package.json
Labels: internal

#297 fix(date-picker): Ranges overlapping the calendar after a certain amount.
  assets/scss/shared-ui/_calendar-range.scss
Labels: bug

#298 fix(calendar): Looking off in mobile.
  assets/scss/shared-ui/_calendar-range.scss
Labels: bug

#405 🐛 fix: RTL styles not being applied.
  CHANGELOG.md
  assets/scss/shared-ui/_mixins.scss
Labels: bug

#403 docs(showcase): Set correct icon markup.
  _layouts/search.html
  assets/js/shared-ui/multistrings.js
  assets/js/shared-ui/notifications.js
  assets/js/showcase/pages/icons.js
  page-icon-buttons.html
  page-select.html
Labels: documentation
