Repository wpmudev/shared-ui, pull requests merged in 2021-09, with the labels that each got.

#335 📝 docs(utilities): Create new page.
  _config.yml
  page-upsell-notice.html
  page-utilities.html
Labels: documentation

#336 📝 docs(accordions): Toggles are using an outdated markup.
  CHANGELOG.md
  page-accordions.html
Labels: documentation

#337 📝 docs(tabs): Notification is using an outdated markup.
  CHANGELOG.md
  page-tabs.html
Labels: documentation

#338 📝 docs(buttons): Review the use of the `role="button"` attribute.
  CHANGELOG.md
  page-buttons.html
Labels: documentation

#339 🐛 fix(toggles): Improve disabled state for "on" and "off" modes.
  CHANGELOG.md
  assets/scss/shared-ui/_toggles.scss
  page-toggles.html
Labels: documentation

#342 📝 docs(notifications): Clean-up and improve documentation.
  assets/js/showcase/pages/notifications.js
  page-notifications.html
Labels: documentation

#343 🐛 fix(typography): Descriptions need to be multi-line.
  assets/scss/shared-ui/_box-settings.scss
  assets/scss/shared-ui/_color-accessibility.scss
  assets/scss/shared-ui/_forms.scss
  assets/scss/shared-ui/_toggles.scss
  assets/scss/shared-ui/_typography.scss
  page-trees.html
  page-utilities.html
Labels: enhancement

#344 🐛 fix(accordions): Remove paragraph overwriting styles.
  assets/scss/shared-ui/_accordions.scss
Labels: bug
