Repository wpmudev/shared-ui, pull requests merged in 2022-04, with the labels that each got.

#487 🐛 fix(builder): Select dropdown list appears behind checkbox items.
  assets/scss/shared-ui/_box-builder.scss
Labels: bug

#490 fix(upgrade-page): Styling issues between the upgrade page and the recommended plugins notice.
  assets/scss/shared-ui/_upgrade-page.scss
Labels: bug

#489 fix(accordions): Focus on content when accordion opens.
  assets/js/shared-ui/accordion.js
Labels: improvement

#424 docs(slide-modal): Slide modal example doesn't work.
  page-modals.html
Labels: documentation

#459 fix(pagination): Element doesn't look good on mobiles.
  assets/scss/shared-ui/_pagination.scss
Labels: bug

#493 fix(button): Update buttons on the showcase.
  _layouts/search.html
  assets/js/shared-ui/code-snippet.js
  assets/js/shared-ui/password.js
  assets/js/showcase/pages/buttons.js
  assets/js/showcase/pages/heading.js
  assets/js/showcase/pages/modals.js
  assets/js/showcase/pages/notifications.js
  assets/scss/shared-ui/_sui-button/_button-modifiers/_button-size.scss
  page-accordions.html
  page-builder.html
  page-buttons.html
  page-footer.html
  page-heading.html
  page-modals.html
  page-notifications.html
  page-password.html
  page-tables.html
  page-tooltips.html
  page-upgrade-demo.html
  page-upgrade.html
  page-upsell-box.html
  page-upsell-notice.html
  page-upsell-widget.html
  search.html
Labels: documentation

#496 docs(notifications): Specifications table is duplicated.
  page-notifications.html
Labels: documentation

#413 new(spotlight): Create new component.
  _config.yml
  assets/js/showcase/pages/notifications.js
  assets/scss/shared-ui/_spotlight.scss
  assets/scss/shared-ui/shared-ui.scss
  page-alert-notice.html
  page-spotlight.html
Labels: new

#497 fix(input): Disabled state styles are missing.
  assets/scss/shared-ui/_forms.scss
  page-inputs.html
Labels: bug
