Repository wpmudev/shared-ui, pull requests merged in 2022-02, with the labels that each got.

#455 fix(snyk): Duplicated import in package.json file.
  .gitignore
  gulpfile.js
Labels: internal

#461 fix(select2): Multi-select with fixed height.
  assets/scss/shared-ui/_select2.scss
Labels: bug

#462 docs(color-picker): Auto-fill does whatever it wants.
  _config.yml
  page-colour-picker.html
Labels: documentation

#448 fix(modals): When the title gets center-aligned, it cuts off with an ellipsis.
  assets/scss/shared-ui/_modals.scss
  page-modals.html
Labels: improvement

#464 fix(tabs): Function `init` has no return statements.
  assets/js/shared-ui/tabs.js
Labels: bug

#465 fix(multistrings): Undefined is not a possible return value of `typeof`.
  assets/js/shared-ui/multistrings.js
Labels: bug

#466 fix(tabs): Function `setCallback` takes 0 parameter(s).
  assets/js/shared-ui/tabs.js
Labels: bug

#467 fix(tabs): On `keyDownEventListener` the body of case clause duplicates.
  assets/js/shared-ui/tabs.js
Labels: bug
