Repository wpmudev/shared-ui, pull requests merged in 2022-09, with the labels that each got.

#486 aria(dropdown): Red buttons don't change color.
  assets/scss/shared-ui/_color-accessibility.scss
Labels: accessibility

#514 aria(side-tabs): Tabs not visible in high-contrast mode.
  assets/scss/shared-ui/_tabs.scss
Labels: accessibility

#516 aria(icon): Required icon in high-contrast mode.
  assets/scss/shared-ui/_utility.scss
Labels: accessibility

#517 aria(calendar): Date picker in high-contrast mode.
  assets/js/showcase/globals/admin-bar.js
  assets/scss/shared-ui/_calendar-range.scss
  assets/scss/shared-ui/_calendar.scss
  page-calendar.html
Labels: accessibility

#454 aria(icons): RTL mode switch icons.
  assets/scss/shared-ui/_icons.scss
Labels: accessibility

#527 aria(progress-bar): Make element properly accessible.
  page-progress-bar.html
Labels: accessibility

#528 aria(select2): Screen readers improvement.
  assets/js/shared-ui/select2.full.js
Labels: accessibility

#433 docs(box): Box header title documentation updated.
  page-box-basics.html
Labels: documentation

#526 fix(insert-variables): Removed first item as selected.
  assets/js/shared-ui/select2.js
Labels: bug

#520 fix(accordions): Content overflows when hidden.
  assets/scss/shared-ui/_accordions.scss
Labels: bug

#533 fix(accordion): Focus design improvement when content opens.
  assets/js/shared-ui/accordion.js
  assets/scss/shared-ui/_accordions.scss
Labels: improvement

#534 fix(variables): Make fonts GDPR compliant.
  assets/scss/shared-ui/_variables.scss
Labels: bug

#535 fix(styles): Manually update SUI version for SCSS files.
  assets/scss/shared-ui/_variables.scss
Labels: bug
