Repository wpmudev/shared-ui, pull requests merged in 2022-05, with the labels that each got.

#499 fix(input): Disabled state styles are missing.
  assets/scss/shared-ui/_forms.scss
  page-inputs.html
Labels: bug

#500 docs(showcase): Set correct icon markup.
  _layouts/search.html
  assets/js/shared-ui/multistrings.js
  assets/js/shared-ui/notifications.js
  assets/js/showcase/pages/icons.js
  page-icon-buttons.html
  page-select.html
Labels: documentation

#501 docs(notifications): Specifications table is duplicated.
  page-notifications.html
Labels: documentation

#502 aria(side-tabs): Required roles ARIA attribute not present.
  assets/js/shared-ui/side-tabs.js
  page-side-tabs.html
Labels: accessibility

#503 docs(modal): Slide modal example doesn't work.
  page-modals.html
Labels: documentation

#504 fix(pagination): Element doesn't look good on mobiles.
  assets/scss/shared-ui/_pagination.scss
Labels: bug

#508 fix(calendar): Looking off in mobile.
  assets/scss/shared-ui/_calendar-range.scss
Labels: bug

#509 fix(calendar): Ranges overlapping the calendar after a certain amount.
  assets/scss/shared-ui/_calendar-range.scss
Labels: bug

#510 fix(upload): Focus state styles are missing.
  assets/scss/shared-ui/_upload.scss
Labels: bug

#449 fix(insert-variables): Dropdown option invisible on hover.
  assets/scss/shared-ui/_select2.scss
Labels: bug

#431 docs(side-navigation): Tabs list doesn't get converted into a select menu on small screens.
  assets/js/showcase/globals/side-navigation.js
  page-accordions.html
  page-box-basics.html
  page-box-message.html
  page-box-settings.html
  page-builder.html
  page-buttons.html
  page-calendar.html
  page-checkbox.html
  page-code-snippets.html
  page-dropdowns.html
  page-footer.html
  page-form-field.html
  page-icon-buttons.html
  page-icons.html
  page-inputs.html
  page-insert-variables.html
  page-layout.html
  page-modals.html
  page-multistrings.html
  page-notifications.html
  page-pagination.html
  page-password.html
  page-progress-bar.html
  page-radios.html
  page-select.html
  page-selectors.html
  page-sidenav.html
  page-status-dot.html
  page-summary.html
  page-toggles.html
  page-tooltips.html
  page-trees.html
  page-uploads-file.html
  page-uploads-image.html
  page-upsell-box.html
  page-upsell-notice.html
  page-upsell-widget.html
  page-utilities.html
Labels: documentation
