Repository wpmudev/shared-ui, pull requests merged in 2022-03, with the labels that each got.

#469 🐛 fix(modals): If statement have duplicate bodies.
  assets/js/showcase/pages/modals.js
Labels: improvement

#458 fix(uploads): Hoisting of functions declared in blocks is handled differently in different browsers.
  assets/js/shared-ui/upload.js
Labels: improvement

#470 fix(select): Use arrow function instead of anonymous function.
  assets/js/showcase/pages/select.js
Labels: improvement

#472 fix(checkbox): Clickable area is too long.
  assets/scss/shared-ui/_radio-checkbox.scss
Labels: improvement

#441 fix(tabs): Overflow flushed tabs menu doesn't have enough space to place navigation buttons.
  assets/scss/shared-ui/_accordions.scss
  assets/scss/shared-ui/_tabs.scss
Labels: bug

#457 fix(toggle): Clickable area is too long.
  assets/scss/shared-ui/_toggles.scss
Labels: bug

#468 fix(insert-variables): Dropdown shouldn't store the option selected.
  assets/js/showcase/pages/insert-variables.js
Labels: improvement

#481 fix(tabs): Enable radio inputs for side-tab buttons.
  _config.yml
  assets/js/shared-ui/tabs.js
  page-side-tabs.html
  page-tabs.html
Labels: improvement

#474 fix(select): The dropdown list is not changing colours when High Contrast Mode is enabled.
  assets/js/shared-ui/select2.js
  assets/js/showcase/globals/admin-bar.js
  assets/scss/shared-ui/_color-accessibility.scss
Labels: bug

#420 fix(showcase): Add `alt` tags to all sample images.
  404.html
  page-box-message.html
  page-builder.html
  page-footer.html
  page-insert-variables.html
  page-modals.html
  page-select.html
Labels: internal

#476 docs(showcase): Add an accessibility state table or similar to keep track of SUI elements status.
  assets/css/showcase.css
  assets/css/showcase.min.css
  assets/js/clipboard.min.js
  assets/js/shared-ui.min.js
  assets/js/showcase.min.js
  assets/js/showcase/globals/table-specifications.js
  page-accordions.html
  page-box-basics.html
  page-box-message.html
  page-box-search.html
  page-box-settings.html
  page-box-status.html
  page-builder.html
  page-buttons.html
  page-calendar.html
  page-checkbox.html
  page-code-editor.html
  page-code-snippets.html
  page-dropdowns.html
  page-field-list.html
  page-form-field.html
  page-icon-buttons.html
  page-inputs.html
  page-insert-variables.html
  page-labels.html
  page-modals.html
  page-multistrings.html
  page-notifications.html
  page-pagination.html
  page-password.html
  page-progress-bar.html
  page-radios.html
  page-recipient.html
  page-scores.html
  page-select.html
  page-selectors.html
  page-side-tabs.html
  page-sidenav.html
  page-status-dot.html
  page-summary.html
  page-tables.html
  page-tabs.html
  page-tags.html
  page-textarea.html
  page-toggles.html
  page-tooltips.html
  page-trees.html
  page-typography.html
  page-upgrade.html
  page-uploads-file.html
  page-uploads-image.html
  page-upsell-notice.html
  page-upsell-widget.html
  page-wp-editor.html
Labels: documentation

#453 fix(code-snippet): "Copy" button triggers the form submission.
  assets/js/shared-ui/code-snippet.js
Labels: bug

#414 fix(code-editor): ACE conflict with WPBakery Page Builder.
  assets/js/shared-ui/ace/ace.js
Labels: bug

#482 fix(toggles): Slider element not aligning correctly when label or description or both are not present.
  assets/scss/shared-ui/_toggles.scss
Labels: bug

#484 fix(toggles): Not registering the event in React with a mapped `onChange` event.
  assets/scss/shared-ui/_toggles.scss
Labels: bug

#475 fix(settings-box): Improve component in RTL mode.
  assets/scss/shared-ui/_box-settings.scss
Labels: bug

#427 fix(selectors): Improve the element for better accessibility.
  page-selectors.html
Labels: improvement

#432 fix(builder): Screen reader does not navigate correctly through the component.
  assets/js/shared-ui/accordion.js
  assets/scss/shared-ui/_box-builder.scss
  assets/scss/shared-ui/_tooltips.scss
  page-builder.html
Labels: improvement

#417 fix(input): Hide option doesn't show when clicking on the icon in the password input.
  assets/js/shared-ui/password.js
Labels: bug
